=== hubmapconsortium-graveyard/prov-vis/src/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/hubmapconsortium/prov-vis/#schema",
  "title": "HuBMAP PROV schema",
  "type": "object",
  "definitions": {
    "string_to_string": {
      "type": "object",
      "patternProperties": {
        ".": {
          "type": "string"
        }
      }
    },
    "string_to_string_to_string": {
      "type": "object",
      "patternProperties": {
        ".": {
          "$ref": "#/definitions/string_to_string"
        }
      }
    }
  },
  "additionalProperties": false,
  "required": ["prefix", "entity", "activity", "wasGeneratedBy", "used"],
  "properties": {
    "prefix": {
      "allOf": [
        { "$ref": "#/definitions/string_to_string" },
        { "$comment": "TODO: Add 'prov'." }
      ]
    },
    "entity": { "$ref": "#/definitions/string_to_string_to_string" },
    "activity": { "$ref": "#/definitions/string_to_string_to_string" },
    "wasGeneratedBy": { "$ref": "#/definitions/string_to_string_to_string" },
    "used": { "$ref": "#/definitions/string_to_string_to_string" },
    "agent": { "$ref": "#/definitions/string_to_string_to_string" },
    "actedOnBehalfOf": { "$ref": "#/definitions/string_to_string_to_string" }
  }
}

=== hubmapconsortium-graveyard/prov-vis/tests/fixtures/real-prov.json
{
  "prefix": {
    "ex": "http://example.org/",
    "hubmap": "https://hubmapconsortium.org/",
    "dct": "http://purl.org/dc/terms/",
    "foaf": "http://xmlns.com/foaf/0.1/",
    "prov": "http://www.w3.org/ns/prov#"
  },
  "agent": {
    "hubmap:agent/e19adbbb-73c3-43a7-b05e-0eead04f5ff8": {
      "hubmap:userEmail": "shirey@pitt.edu",
      "hubmap:userUUID": "e19adbbb-73c3-43a7-b05e-0eead04f5ff8",
      "hubmap:userDisplayName": "William Shirey",
      "prov:type": "prov:Person"
    },
    "hubmap:organization/5bd084c8-edc2-11e8-802f-0e368f3075e8": {
      "hubmap:groupName": "hubmap-testing",
      "hubmap:groupUUID": "5bd084c8-edc2-11e8-802f-0e368f3075e8",
      "prov:type": "prov:Organization"
    }
  },
  "entity": {
    "hubmap:entities/0817f6a3a2f170486a49f2ffae46072d": {
      "prov:label": "TEST0005-RK-4",
      "prov:type": "Sample",
      "hubmap:doi": "576RGJR357",
      "hubmap:displayDOI": "HBM:576-RGJR-357",
      "hubmap:displayIdentifier": "TEST0005-RK-4",
      "hubmap:uuid": "0817f6a3a2f170486a49f2ffae46072d",
      "hubmap:metadata": "{\"protocols\": \"[{'id': 'protocol_1', 'protocol_url': 'http://protocols.io/protst/29022928394', 'protocol_file': ''}]\", \"specimen_type\": \"fresh_frozen_tissue\", \"user_group_uuid\": \"5bd084c8-edc2-11e8-802f-0e368f3075e8\", \"sample_count\": \"5\"}",
      "prov:generatedAtTime": "2019-09-17T16:40:04",
      "hubmap:modifiedTimestamp": "2019-09-17T16:40:04"
    },
    "hubmap:entities/12e77e69ab76b1832a95e00646f666db": {
      "prov:label": "TEST0005-RK-5",
      "prov:type": "Sample",
      "hubmap:doi": "555JCVC476",
      "hubmap:displayDOI": "HBM:555-JCVC-476",
      "hubmap:displayIdentifier": "TEST0005-RK-5",
      "hubmap:uuid": "12e77e69ab76b1832a95e00646f666db",
      "hubmap:metadata": "{\"protocols\": \"[{'id': 'protocol_1', 'protocol_url': 'http://protocols.io/protst/29022928394', 'protocol_file': ''}]\", \"specimen_type\": \"fresh_frozen_tissue\", \"user_group_uuid\": \"5bd084c8-edc2-11e8-802f-0e368f3075e8\", \"sample_count\": \"5\"}",
      "prov:generatedAtTime": "2019-09-17T16:40:04",
      "hubmap:modifiedTimestamp": "2019-09-17T16:40:04"
    },
    "hubmap:entities/d2f87dda666fce9efeeeb09b078b5feb": {
      "prov:label": "TEST0005-RK-3",
      "prov:type": "Sample",
      "hubmap:doi": "479XQZH692",
      "hubmap:displayDOI": "HBM:479-XQZH-692",
      "hubmap:displayIdentifier": "TEST0005-RK-3",
      "hubmap:uuid": "d2f87dda666fce9efeeeb09b078b5feb",
      "hubmap:metadata": "{\"protocols\": \"[{'id': 'protocol_1', 'protocol_url': 'http://protocols.io/protst/29022928394', 'protocol_file': ''}]\", \"specimen_type\": \"fresh_frozen_tissue\", \"user_group_uuid\": \"5bd084c8-edc2-11e8-802f-0e368f3075e8\", \"sample_count\": \"5\"}",
      "prov:generatedAtTime": "2019-09-17T16:40:04",
      "hubmap:modifiedTimestamp": "2019-09-17T16:40:04"
    },
    "hubmap:entities/731c5b88cdc623212cf605d1ff6f22f7": {
      "prov:label": "TEST0005-RK-2",
      "prov:type": "Sample",
      "hubmap:doi": "876VBCH275",
      "hubmap:displayDOI": "HBM:876-VBCH-275",
      "hubmap:displayIdentifier": "TEST0005-RK-2",
      "hubmap:uuid": "731c5b88cdc623212cf605d1ff6f22f7",
      "hubmap:metadata": "{\"protocols\": \"[{'id': 'protocol_1', 'protocol_url': 'http://protocols.io/protst/29022928394', 'protocol_file': ''}]\", \"specimen_type\": \"fresh_frozen_tissue\", \"user_group_uuid\": \"5bd084c8-edc2-11e8-802f-0e368f3075e8\", \"sample_count\": \"5\"}",
      "prov:generatedAtTime": "2019-09-17T16:40:04",
      "hubmap:modifiedTimestamp": "2019-09-17T16:40:04"
    },
    "hubmap:entities/51318fa4fff79c82d4de7b2d70e630cb": {
      "prov:label": "TEST0005-RK-1",
      "prov:type": "Sample",
      "hubmap:doi": "836PZMN835",
      "hubmap:displayDOI": "HBM:836-PZMN-835",
      "hubmap:displayIdentifier": "TEST0005-RK-1",
      "hubmap:uuid": "51318fa4fff79c82d4de7b2d70e630cb",
      "hubmap:metadata": "{\"protocols\": \"[{'id': 'protocol_1', 'protocol_url': 'http://protocols.io/protst/29022928394', 'protocol_file': ''}]\", \"specimen_type\": \"fresh_frozen_tissue\", \"user_group_uuid\": \"5bd084c8-edc2-11e8-802f-0e368f3075e8\", \"sample_count\": \"5\"}",
      "prov:generatedAtTime": "2019-09-17T16:40:04",
      "hubmap:modifiedTimestamp": "2019-09-17T16:40:04"
    }
  },
  "wasGeneratedBy": {
    "_:id1": {
      "prov:entity": "hubmap:entities/0817f6a3a2f170486a49f2ffae46072d",
      "prov:activity": "hubmap:activities/822a66f8d498ef37fbc2280abcf56c9e"
    },
    "_:id2": {
      "prov:entity": "hubmap:entities/12e77e69ab76b1832a95e00646f666db",
      "prov:activity": "hubmap:activities/822a66f8d498ef37fbc2280abcf56c9e"
    },
    "_:id3": {
      "prov:entity": "hubmap:entities/d2f87dda666fce9efeeeb09b078b5feb",
      "prov:activity": "hubmap:activities/822a66f8d498ef37fbc2280abcf56c9e"
    },
    "_:id4": {
      "prov:entity": "hubmap:entities/731c5b88cdc623212cf605d1ff6f22f7",
      "prov:activity": "hubmap:activities/822a66f8d498ef37fbc2280abcf56c9e"
    },
    "_:id5": {
      "prov:entity": "hubmap:entities/51318fa4fff79c82d4de7b2d70e630cb",
      "prov:activity": "hubmap:activities/822a66f8d498ef37fbc2280abcf56c9e"
    }
  },
  "activity": {
    "hubmap:activities/822a66f8d498ef37fbc2280abcf56c9e": {
      "prov:startTime": "2019-09-17T16:40:04",
      "prov:endTime": "2019-09-17T16:40:04",
      "prov:label": "822a66f8d498ef37fbc2280abcf56c9e",
      "prov:type": "Create Sample Activity",
      "hubmap:doi": "982TNDD845",
      "hubmap:displayDOI": "HBM:982-TNDD-845",
      "hubmap:displayIdentifier": "822a66f8d498ef37fbc2280abcf56c9e",
      "hubmap:uuid": "822a66f8d498ef37fbc2280abcf56c9e",
      "prov:generatedAtTime": "2019-09-17T16:40:04",
      "hubmap:modifiedTimestamp": "2019-09-17T16:40:04"
    }
  },
  "actedOnBehalfOf": {
    "_:id6": {
      "prov:delegate": "hubmap:agent/e19adbbb-73c3-43a7-b05e-0eead04f5ff8",
      "prov:responsible": "hubmap:organization/5bd084c8-edc2-11e8-802f-0e368f3075e8",
      "prov:activity": "hubmap:activities/822a66f8d498ef37fbc2280abcf56c9e"
    }
  },
  "used": {
    "_:id7": {
      "prov:activity": "hubmap:activities/822a66f8d498ef37fbc2280abcf56c9e",
      "prov:entity": "hubmap:entities/9942c58c009cb0a0f245f9cb61586af5"
    }
  }
}
